export const UserTypes = {
  CREATE: "CREATE_USER",
  CREATE_FAIL: "CREATE_USER_FAIL",
  CREATE_SUCCESS: "CREATE_USER_SUCCESS",
  SET_IS_LOADING: "SET_IS_LOADING_USER",
  CLEAR_NOTIFICATION: "CLEAR_NOTIFICATION_USER",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAIL: "UPDATE_USER_FAIL",
  //
  GET_All_USER: "GET_All_USER",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_BY_ID: "GET_USER_BY_ID",
  GET_USER_BY_ID_SUCCESS: "GET_USER_BY_ID_SUCCESS",
  SET_LOADING: "SET_LOADING",
};

export const AuthTypes = {
  LOGIN: "LOGIN",
  LOGIN_FAIL: "LOGIN_FAIL",
  SET_LOADING: "SET_LOADING",
  GET_All_USER: "GET_All_USER",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT: "LOGOUT",
  CHANGE_PROFILE: "CHANGE_PROFILE",

  AUTH_LOCALSTORAGE: "AUTH_LOCALSTORAGE",
};

export const ModalTypes = {
  SHOW: "ISSHOW",
  HIDE: "HIDE",
};

export const HeaderType = {
  GET_HEIGHT: "GET_HEIGHT",
};

export const ProductTypes = {
  GET_All_PRODUCT: "GET_All_PRODUCT",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  SET_LOADING: "SET_LOADING",
  GET_PRODUCT_BY_FILTER: "GET_PRODUCT_BY_FILTER",
  GET_PRODUCT_BY_FILTER_PRICE: "GET_PRODUCT_BY_FILTER_PRICE",
  GET_PRODUCT_BY_GENDER: "GET_PRODUCT_BY_GENDER",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  GET_PRODUCT_BY_ID_SUCCESS: "GET_PRODUCT_BY_ID_SUCCESS",
  GET_PRODUCT_BY_PAGE: "GET_PRODUCT_BY_PAGE",
  GET_PRODUCT_BY_NAME: "GET_PRODUCT_BY_NAME",
};

export const CartType = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_TO_CART: "REMOVE_TO_CART",
  GET_ALL_CART: "GET_ALL_CART",
  SET_LOADING: "SET_LOADING",
  CHECK_OUT: "CHECK_OUT",
  CHANGE_QUANTITY_CART: "CHANGE_QUANTITY_CART",
  CHANGE_WISH_LIST: "CHANGE_WISH_LIST ",
  REMOVE_ALL_CART: "REMOVE_ALL_CART",

  CART_LOCALSTORAGE: "cartProduct",
};

export const CategoryTypes = {
  GET_All_CATEGORY: "GET_All_CATEGORY",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  SET_LOADING: "SET_LOADING",
};

export const OrderTypes = {
  GET_All_ORDER: "GET_All_ORDER",
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
  GET_ORDER_BY_FILTER: "GET_ORDER_BY_FILTER",
  GET_ORDER_BY_ID: "GET_ORDER_BY_ID",
  GET_ORDER_BY_ID_SUCCESS: "GET_ORDER_BY_ID_SUCCESS",
  SET_LOADING: "SET_LOADING",
  ADD_ORDER: "ADD_ORDER",
  GET_ORDER_BY_PROFILE: "GET_ORDER_BY_PROFILE",
};

export const RatingTypes = {
  GET_RATINGS: "GET_RATINGS",
  GET_RATING_BY_FILTER: "GET_RATING_BY_FILTER",
  GET_RATING_SUCCESS: "GET_RATING_SUCCESS",
  GET_RATING_BY_PAGE: "GET_RATING_BY_PAGE",
  LAST_DATA_RATING: "LAST_DATA_RATING",
  SET_LOADING: "SET_LOADING",
  ADD_RATING: "ADD_RATING",
};

export const Status = {
  PROCESSING: "PROCESSING",
  SHIPPING: "SHIPPING",
  DELIVERED: "DELIVERED",
  CANCELED: "CANCELED",
};

export const PaymentTypes = {
  MOMO: "MOMO",
  VISA: "VISA",
  PAYPAL: "PAYPAL",
  BANK: "BANK",
};

export const LocalKey = {
  THEME: "theme",
};
